name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: make
    - name: make tests
      run: make tests_run
