name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install build-essential
      run: sudo apt-get install build-essential
    - name: build
      run: make
    - name: make tests
      run: make tests_run
